# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5223d34f9e5f4df957ab279a17e28d74f6f4512e15c9554ef07e344901007dc3a6ae96c3c2493925f43c0d037312155c14259eea947e41ecf56579b58bd23107

test:
  secret_key_base: 98aae96ce2a04ea6c508114b5824c023d3491215490824ee9c1522733c1a402d6bb0d864441d070a42d27c904b2686c0dba8f05d4d66c834860d9353cb634c88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
