# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec93a10181af6dac90dcf159fda10b7ac2e980e73dc75c3680cf639a0dd00dcca2735ee383151cbf549b28a215c4c533237ef733838368c3da26a9ff87e1944

test:
  secret_key_base: 2b7519d2eda4000747ef3768df8106596b1e1e8d1854a31d1c5c2b567cf772dc6e0053646be4df72c43b345883495c0f88cb26e57fe5373b8ad7f4d56d164dd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
