# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a7a0acdc6e17f996216062fa4811f88723daaff22d1ede467f80bcded85dc1f368f6fa2585f632943e270f1d7a0cf1c0d3f5b449a80950b2bfdceb222cb7134

test:
  secret_key_base: 232397b3cc163f9750c8ac0be4046ef6d92cf942538c678d3d1d3d42ef7cd9b3769dad0dbb65527929fb38474264f4f21ab09c3d6dbc50e6cb251a60f419424e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
